sudo: required
language: go

go:
  - 1.4.2

# TODO: restore this when Travis will supply a docker compatible environment
# NOTE: Currently, Travis run our tests inside a docker container running with an old kernel not supported by docker
# install:
#   - sudo wget -qO- https://get.docker.com/ | sh
#   - docker --version
#   - sudo usermod -aG docker `whoami`
#   - sudo docker -d

script:
- cd src
- go test

env: GOPATH /srv

script:
    - go test ./...
