watcher:
    build: ./var/dockerfile/go/
    volumes:
        - ./src:/srv
        - /var/lib/docker:/var/lib/docker
        - /var/lib/docker-compose:/var/lib/docker-compose
    command: sleep 123456789
    privileged: true
    ports:
        - "3000:80"
